// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";

// In local dev, load .env.local. On Vercel, env vars are already injected
// into process.env from the dashboard, so this is a harmless no-op there.
if (process.env.NODE_ENV !== "production") {
  dotenv.config({ path: ".env.local" });
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
